///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest37
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest37Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("62544f83-7b3a-4f22-a960-d212d3cf2120")]
    public partial class MyTest37Repository : RepoGenBaseFolder
    {
        static MyTest37Repository instance = new MyTest37Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest37Repository element repository.
        /// </summary>
        [RepositoryFolder("62544f83-7b3a-4f22-a960-d212d3cf2120")]
        public static MyTest37Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest37Repository() 
            : base("MyTest37Repository", "/", null, 0, false, "62544f83-7b3a-4f22-a960-d212d3cf2120", ".\\RepositoryImages\\MyTest37Repository62544f83.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("62544f83-7b3a-4f22-a960-d212d3cf2120")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest37RepositoryFolders
    {
    }
#pragma warning restore 0436
}
